### ISSUE TITLE
Use openblas instead of lapack

### ISSUE THREAD

**Issue by isuruf** [conda-forge/jags-feedstock#2]
conda-forge is using openblas which comes with lapack. You also need to rerender after changing the requirement

**Comment by micknudsen** [comment]
When I run `conda smithy rerender`, the result is `No changes made. This feedstock is up-to-date.` What am I missing here?

**Comment by isuruf** [comment]
@micknudsen, can you open a PR with the change made and ping me and I can help with the rerendering.

**Comment by micknudsen** [comment]
@isuruf Which changes?

**Comment by isuruf** [comment]
Change lapack to openblas

**Comment by micknudsen** [comment]
Ah, I misunderstood everything. I thought your issue related to the latest pull request merge (that rerendering for that had not been performed).

New PR: https://github.com/conda-forge/jags-feedstock/pull/3

**Comment by micknudsen** [comment]
Merged
